name: Check Code Style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Basic read permissions only needed now
permissions:
  contents: read

jobs:
  pint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Laravel Pint (Check only)
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true